version: '3.9'

services:
  go-app:
    container_name: go-app
    image: ikukla/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go_db user={user} password={password} dbname={dbname} sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: {password}
      POSTGRES_USER: {user}
      POSTGRES_DB: {dbname}
    ports:
      - "{port}:{port}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
